### ISSUE TITLE
GC collection/ pause/ heap metrics not available when running GC in Server mode

### ISSUE THREAD

**Issue by djluck** [djluck/prometheus-net.DotNetRuntime#1]
This is a result of this [Core CLR issue](https://github.com/dotnet/coreclr/issues/21380)- hopefully it should be resolved soon.

**Comment by snehashankar** [comment]
Is the fix made in .Net core 2.2 or 3?

**Comment by djluck** [comment]
@snehashankar It should be 3.0. The above issue has been marked as closed but I have not yet tested it. I will do so when 3.0 is made available.

**Comment by djluck** [comment]
Fix has been confirmed in the .NET 3.0 preview.
