### ISSUE TITLE
Using with MetricPusher

### ISSUE THREAD

**Issue by oceandrama** [djluck/prometheus-net.DotNetRuntime#13]
Hi. Can I use it with MetricPusher? I can't use MetricServer because Prometheus works in Docker in its own network, and I want to send metrics from localhost, when I running application from Visual Studio.

**Comment by djluck** [comment]
Hey @oceandrama, MetricPusher should be fine (although I've not tested it myself).

**Comment by oceandrama** [comment]
Should I do something besides?
```
DotNetRuntimeStatsBuilder.Default().StartCollecting();
var pusher = new MetricPusher("http://localhost:9091", "pushgateway");
pusher.Start();
```

**Comment by djluck** [comment]
`DotNetRuntimeStatsBuilder.Default().StartCollecting()` will hook into the `prometheus-net` library and start collecting metrics about the .NET runtime- there's little else you need to do.
