### ISSUE TITLE
Also target .NET Standard 2.1

### ISSUE THREAD

**Issue by blankensteiner** [djluck/prometheus-net.DotNetRuntime#21]
Seems like all that is needed for this to work is to add it as a target framework in prometheus-net.DotNetRuntime.csproj:

`<TargetFrameworks>netcoreapp2.2;netcoreapp3.0;netstandard2.1</TargetFrameworks>`

And then add this dependency:

```
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
  <PackageReference Include="System.Collections.Immutable" Version="1.6.0" />
</ItemGroup>
```

Would that be possible? I can create a PR for it if you want.

**Comment by djluck** [comment]
Hey @blankensteiner, unfortunately this is not the case- the events that drive this library are only present in .net core 2.2+.

**Comment by blankensteiner** [comment]
Hi James. Please correct me if I am wrong, but is it not just the executing runtime that has to be .NET Core 2.2+? If I change the assembly to .NET Standard 2.1, then tests still pass.
I was just thinking that if it works as a .NET Standard 2.1 assembly, then the same version can be used from all runtimes supporting it, but the user would have to ensure that the events are present. I don't know if they are in Xamarin or are going to be in Unity and so on.

**Comment by djluck** [comment]
I actually hadn't considered that possibility but yeah, that would make sense. I think this could be done, if you'd like to make a PR I'd be happy to accept it.

**Comment by djluck** [comment]
Resolved by https://github.com/djluck/prometheus-net.DotNetRuntime/pull/22.

**Comment by djluck** [comment]
Released: https://github.com/djluck/prometheus-net.DotNetRuntime/releases/tag/v3.3.0.
