### ISSUE TITLE
Should process_cpu_seconds_total be exported?

### ISSUE THREAD

**Issue by MacroPower** [djluck/prometheus-net.DotNetRuntime#26]
Question/Possible Bug

I've noticed that in the example Grafana dashboards, included is a `process_cpu_seconds_total` metric. This is used with `process_cpu_count`. 

`process_cpu_count` is working fine for me, but `process_cpu_seconds_total` is not being published.

However, I can't find this metric anywhere in this repo. So, I'm not actually sure if this is a bug or not. I would have assumed this was just an oversight on the part of the dashboard, and the metric is actually coming from some other source... but `process_cpu_count` **is** published, which makes me think that `process_cpu_seconds_total` should be published as well.

So, should `process_cpu_seconds_total` be exported? If not, where should we be obtaining that metric for the example Grafana dashboard?

**Comment by djluck** [comment]
Hey @MacroPower,

So `process_cpu_seconds_total` is exposed by [prometheus-net](https://github.com/prometheus-net/prometheus-net/blob/3106c225deadd5249a0beb7f3eaac7344c28700c/Prometheus.NetStandard/DotNetStats.cs#L51). If you call `Metrics.SuppressDefaultMetrics()`, then this metric won't be collected, is it possible you've called this?

**Comment by MacroPower** [comment]
@djluck Ah, I see. I was using a custom registry for prometheus-net.DotNetRuntime, so those metrics were not being created. They do get created in the default one.

I took a look at prometheus-net, and it looks like I can probably just use `DotNetStats.Register(myCustomRegistry)` to append these stats to my custom registry.
