### ISSUE TITLE
Unable to call app.UseMetricServer(); in my .net core 3.1 application

### ISSUE THREAD

**Issue by KamranShahid** [djluck/prometheus-net.DotNetRuntime#28]
I have just referenced this library (version 3.3.0) in my asp.net core 3.1 web api project
But in my startup class i am not able call app.UseMetricServer

as mentioned in 
https://github.com/djluck/prometheus-net.DotNetRuntime/blob/master/examples/AspNetCoreExample/Startup.cs

any particular thing i am missing?

**Comment by djluck** [comment]
You need to add a reference to the `prometheus-net.AspNetCore` nuget package.

**Comment by KamranShahid** [comment]
> prometheus-net.AspNetCore

I had added the reference

**Comment by f2calv** [comment]
I can confirm this package isn't happy with running in a 3.1 application;
![image](https://user-images.githubusercontent.com/16097639/73424070-2960fc80-432e-11ea-82f6-a67d636875eb.png)

**Comment by djluck** [comment]
@f2calv can you double check that your project is indeed targeting .NET core 2.2+? Judging by the error you're targeting .NET standard 2.0.

**Comment by f2calv** [comment]
OK so it was my problem... surprise surprise :)
I had some intermediary class libraries on NET Standard 2.0 and I didn't want to upgrade them to 2.1 - but now I have done some TargetFramework 'juggling' it's all working now, thanks
