### ISSUE TITLE
Disposable object exception

### ISSUE THREAD

**Issue by bugs-x64** [djluck/prometheus-net.DotNetRuntime#34]
Use .NET Core 3.1 WebApi

**Preparing steps**:
1) add this code in Configure method (**Startup.cs**)

```csharp
        public override void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
             DotNetRuntimeStatsBuilder.Default().StartCollecting(); 
        }
```
2) add **XUnitProject** with two and more classes
```csharp

    namespace foo
    {
        public class FooControllerTests : IClassFixture<WebApplicationFactory<Startup>>
        {
            private readonly WebApplicationFactory<Startup> _factory;

            public FooControllerTests(WebApplicationFactory<Startup> factory)
            {
                _factory = factory;
            }

            [Fact]
            public void TestMethod()
            {
                var client = _factory.CreateClient();
            }
        }

        public class BarControllerTests : IClassFixture<WebApplicationFactory<Startup>>
        {
            private readonly WebApplicationFactory<Startup> _factory;

            public BarControllerTests(WebApplicationFactory<Startup> factory)
            {
                _factory = factory;
            }

            [Fact]
            public void TestMethod()
            {
                var client = _factory.CreateClient();
            }
        }
    }
```
**Execution**:
Run tests in parallel. XUnit will throw exception: ".NET runtime metrics are already being collected. Dispose() of your previous collector before calling this method again."

***Workaround***:
I resloved this by using compilation symbols
```csharp
          #if !DEBUG
            DotNetRuntimeStatsBuilder.Default().StartCollecting();
          #endif
```

But me need more clean solution for this problem. How to do this?

**Comment by djluck** [comment]
The issue I believe you are facing is that you are not disposing the `IDisposable` returned by `DotNetRuntimeStatsBuilder.Default().StartCollecting()`. I'd suggest reading https://andrewlock.net/four-ways-to-dispose-idisposables-in-asp-net-core/#disposing-when-the-application-ends-hooking-into-iapplicationlifetime-events to get some ideas about how you can dispose of the stats collector when your ASP.NET core application is terminated.
