### ISSUE TITLE
Breaking changes in prometheus-net 3.X

### ISSUE THREAD

**Issue by rwkarg** [djluck/prometheus-net.DotNetRuntime#4]
It looks like the old way of registering metrics has moved from the Collector to the Metrics class.
Guidance or updates on how to register these metrics is needed.

**Comment by djluck** [comment]
Hey @rwkarg, yeah I'm aware of the breaking changes. I just need to find some time to re-write how this library integrates with prometheus, shouldn't be too tricky.

Btw, are you actually using this in production currently?

**Comment by rwkarg** [comment]
We have a handful of services that are using this in production but it's not yet pulled in to our standard base template.

**Comment by djluck** [comment]
Thanks for the feedback. As this is still in alpha I want to make it clear not all functionality works (due to bugs in the .NET core runtime) or has been tested thoroughly (still a bit of work on my part to do here). 

I'll try and start on integrating with Prometheus v3 tonight but it might require more than a couple of hours of work.

**Comment by djluck** [comment]
I'm currently blocked by https://github.com/prometheus-net/prometheus-net/issues/136. Until a decision is made, I can't progress with the work. Almost all other work is done however, so once this is resolved a new version that supports v3 shouldn't be too far away.

**Comment by djluck** [comment]
Hey @rwkarg, I've published a new version that targets v3 of prometheus- https://www.nuget.org/packages/prometheus-net.DotNetRuntime/3.0.7-beta. Give it a whirl and let me know how it goes. Just an FYI, the registration of the collector has changed slightly, take a look at the README for more info.

**Comment by rwkarg** [comment]
Unfortunately, we're currently pushing to an in-house metrics backend, not exposing metrics pulled by Prometheus yet. We'll either need to get Prometheus stood up (along with integrating alerts with our existing Ops setup) or get the ability to pull all metrics again to be able to update to prometheus-net.

**Comment by rwkarg** [comment]
We're still in the process of integrating Prometheus with the rest of our Ops pipeline but I've moved a few services to the new 3.X packages and things are looking good.
It's also nice to get the ASP.NET Core metrics as well in the prometheus-net 3.X package.

These are using .NET Core 2.2. Still waiting on some internal dependencies before moving any services to .NET Core 3.0 previews.
