### ISSUE TITLE
Add Support for .net5.0

### ISSUE THREAD

**Issue by dustinchilson** [djluck/prometheus-net.DotNetRuntime#44]
When targeting a 5.0 service this library seems to not fully support .net5.0 targets
![image](https://user-images.githubusercontent.com/69644/99977888-3c3c3600-2d73-11eb-87dc-2ace1ca9c54c.png)

My library mult-targets netcoreapp3.1 and net5.0 and has issues with the 5.0 build.

I forked and got your lib building just fine on 5.0 off master but noticed you had changes/comments in #43 any issue with a PR adding support for net5.0?

**Comment by djluck** [comment]
#43 is a long way from being completed- I can add `net5.0` as a build target in the meantime- thanks for the report.

**Comment by djluck** [comment]
v3.4.1 has been published to nuget, should be visible in the next few hours. Thanks again!
