### ISSUE TITLE
ThreadPool IO thread num is always 0

### ISSUE THREAD

**Issue by WeihanLi** [djluck/prometheus-net.DotNetRuntime#45]
In my application, the `dotnet_threadpool_io_num_threads` metrics is always 0

I use the default stats builder running on `.NET5`

``` csharp
DotNetRuntimeStatsBuilder.Default().StartCollecting();
```

![image](https://user-images.githubusercontent.com/7604648/100113753-a0621580-2eab-11eb-8648-9f0f47fb2f02.png)

![image](https://user-images.githubusercontent.com/7604648/100114078-0189e900-2eac-11eb-9a8e-38fd2c856aed.png)

project is here, if you wanna have a check on my code <https://github.com/OpenReservation/ReservationServer/blob/dev/OpenReservation/Program.cs#L12>

**Comment by djluck** [comment]
Thanks for the report. Out of interest:
- What OS/ environment is this running on?
- What version of the .NET core runtime is this running on?
- Have you tried making requests to the website and do you observe any change in the metric count?

**Comment by WeihanLi** [comment]
Hi @djluck,
I'm running on .NET5 GA alpine based docker container, exactly tag is: `mcr.microsoft.com/dotnet/aspnet:5.0-alpine`
I've tried to request the website, but the thread pool io thread num keeps 0

**Comment by rwkarg** [comment]
Linux doesn't have IOCompletion ports so it doesn't have an IO Completion Port Thread Pool.

0 is accurate.

**Comment by WeihanLi** [comment]
Thanks very much @rwkarg .
