### ISSUE TITLE
Is Fasterflect a required dependency?

### ISSUE THREAD

**Issue by rwkarg** [djluck/prometheus-net.DotNetRuntime#5]
Is this something that can be pulled in as code? It doesn't seem like there is too it uses and it would be nice to keep the dependency list down.

**Comment by djluck** [comment]
Fasterflect was used as a stopgap- I believe this can be removed. I'll try and work on this shortly.

**Comment by djluck** [comment]
Latest version no longer has a dependency on Fasterflect.
