### ISSUE TITLE
Could we get types and the size on the heap

### ISSUE THREAD

**Issue by WeihanLi** [djluck/prometheus-net.DotNetRuntime#50]
Sometimes our application may run into high memory usage, I'm wondering that if we could find what's the main types that cost the most memory.

**Comment by djluck** [comment]
Hey @WeihanLi. This is not something I've looked into although in theory it's possible. However, I'd be wary of trying to implement something like this for the following reasons:
- **Performance impact**- dumping the heap (which is what we would have to do to accomplish your request) is an expensive operation- we'd have to be very careful about how we did this in an automated fashion.
- **Limited utility**- almost every application will see `string` and `byte[]` taking up most of the space. And even if the type does stand out, without knowing the GC root of these objects (which can be complex) it won't help you necessarily understand why memory use has increased.
- **There's a tool for that**- `dotnet gcdump` or `dotnet dump` are designed exactly for this scenario, telling you what is in the heap and what references are being held (GC roots).
- **Complexity**- I'm aware of the mechanisms that allow this to happen but I've never tried to implement heap analysis!

I see this library as a way to monitor memory use over time- in low memory scenarios, you should be taking a memory dump using the above tools to understand why your application is low on memory.

If I've missed a useful scenario or misunderstood your ask, please set me straight!

**Comment by WeihanLi** [comment]
Thanks @djluck
