### ISSUE TITLE
[v4] Latest release fails to work with automated binding redirects

### ISSUE THREAD

**Issue by amis92** [djluck/prometheus-net.DotNetRuntime#52]
In v4 of the package, `AssemblyFileVersion` is `1.0.0.0`. Previous versions had appropriate major.minor from package.

The problem I've encountered is using a dependency that requires v3.4 while I use v4.0. The problem is because my app references an assembly from package v4 that declares `AssemblyFileVersion=1.0.0.0` so it generates a redirect of "0.0.0.0-1.0.0.0=>1.0.0.0", and the dependency I use requires DLL with `AssemblyFileVersion=3.4.0.0` which doesn't fit into the redirect.

Now, if the v4 had `AssemblyFileVersion=4.0.0.0`, the redirect .NET generates would be "0.0.0.0-4.0.0.0=>4.0.0.0", which would be used for the 3.4.0.0 requirement.

I hope I've explained the issue enough, since binding redirects belong in hell... ;)

**Comment by amis92** [comment]
I think the issue should be resolved by changing the following line:

https://github.com/djluck/prometheus-net.DotNetRuntime/blob/91bb6b8e115a7017456de3510d02a54293721581/.github/workflows/publish-nuget-packages.yaml#L20

`-p:PackageVersion=$VERSION` should be replaced with `-p:Version=$VERSION`

The `PackageVersion` defaults to `Version`, while `Version`, if unspecified, defaults to `1.0.0`.

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli#set-properties

**Comment by djluck** [comment]
Thanks for the report and the investigation @amis92- when inspecting the version metadata of the DLLs I can clearly see the version is `1.0.0`. Will try your fix and see how I go with that.
