### ISSUE TITLE
Getting EventSource error in cpu-usage callback

### ISSUE THREAD

**Issue by TETYYS** [djluck/prometheus-net.DotNetRuntime#62]
My program keeps outputing

```
EventSource Error: ERROR: Exception during EventCounter cpu-usage metricProvider callback: Attempted to divide by zero.
```

I only use `prometheus-net.DotNetRuntime` for CPU monitoring, so I assume it comes from this. It doesn't print a stacktrace or anything, so I don't have any more info.

---

```
DotNetRuntimeStatsBuilder
	.Customize()
	.WithContentionStats(CaptureLevel.Informational)
	.WithJitStats()
	.WithThreadPoolStats()
	.WithGcStats(CaptureLevel.Informational)
	.WithExceptionStats()
	.StartCollecting();
```

.NET 5
Windows 20H2

**Comment by djluck** [comment]
Interesting, thanks for the report. So I'm not actually tracking the value of the `cpu-usage` event counter. Do you have a full stack trace to accompany this exception?

**Comment by TETYYS** [comment]
No, sorry, no stacktrace. If you're not tracking that event counter then it might be related to VS debugger.
