### ISSUE TITLE
Add dotnet_build_info

### ISSUE THREAD

**Issue by ArgTang** [djluck/prometheus-net.DotNetRuntime#7]
Hello, 
there seems to be a custom to add a app_build_infoto expose version info. Would it be something to add as default to this package? 

Something like this:

```csharp
var buildversion = Assembly.GetEntryAssembly().GetCustomAttribute<AssemblyFileVersionAttribute>().Version;
var assemblyversion = Assembly.GetEntryAssembly().GetName().Version;
var assemblyname = Assembly.GetEntryAssembly().GetName().Name;
var runtimetargetversion = Assembly.GetEntryAssembly().GetCustomAttribute<TargetFrameworkAttribute>().FrameworkName;
var runtimeversion = RuntimeInformation.FrameworkDescription;
var osversion = RuntimeInformation.OSDescription;

var labels = new string[] { "buildversion", "assemblyversion", "assemblyname", "runtimetargetversion", "runtimeversion", "osversion" };
var labelvalues = new string[] { buildversion, assemblyversion.ToString(), assemblyname, runtimetargetversion, runtimeversion, osversion };
var appinfo = Metrics
                .CreateGauge("dotnet_build_info", "application build information", new GaugeConfiguration
                {
                    LabelNames = labels
                });
appinfo.WithLabels(labelvalues);
```

**Comment by djluck** [comment]
Hey @ArgTang!. Yeah I am aware of that convention but I didn't get round to implementing it- thanks for the prompt. 
I think this should be possible but as it's a plugin to `prometheus-net`, any attempt to publish this metric might clash with either `prometheus-net` or another plugin. I'll have a think.

**Comment by ThomasTosik** [comment]
I would also suggest some addtional runtime information like MachineName. Or does prometheus-net takes already care of it? This would help to distinguish several instances of a service.

**Comment by djluck** [comment]
@ThomasTosik I've generally seen names being set in the Prometheus scrape configuration... I'll have a think about your proposal though.

**Comment by djluck** [comment]
@ArgTang, thanks for the provided code- I was able to use most of it to add in `dotnet_build_info`, you can see a sample here:
```
dotnet_build_info{version="3.1.0.0",target_framework=".NETCoreApp,Version=v2.2",runtime_version=".NET Core 4.6.27817.03",os_version="Microsoft Windows 10.0.17134 ",process_architecture="X64"} 1
```

You can install the latest version of the package (either `3.1.1-beta` or `2.1.1-beta`) to use this feature.

I decided against including the executing application version as I don't believe that belongs in this library. I also decided against MachineName as this should be covered by a Prometheus installation.

**Comment by ArgTang** [comment]
@djluck cool! i'll check it out. is it Toggleable?

**Comment by djluck** [comment]
No, it's just on by default.
